[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = ['denite.nvim']

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'javascriptreact', 'typescriptreact']

[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1

[[plugins]]
repo = 'sjl/gundo.vim'
on_cmd = ['GundoToggle']

#Python
[[plugins]]
repo = 'jmcantrell/vim-virtualenv'
on_ft = ['python', 'python3', 'djangohmtl']

[[plugins]]
repo = 'tell-k/vim-autopep8'
on_ft = ['python', 'python3', 'djangohtml']
hook_source = '''
    function! Preserve(command)
        let search = @/
        let cursor_position = getpos('.')
        normal! H
        let window_position = getpos('.')
        call setpos('.', cursor_position)
        execute a:command
        let @/ = search
        call setpos('.', window_position)
        normal! zt
        call setpos('.', cursor_position)
    endfunction

    function! Autopep8()
        call Preserve(':silent %!autopep8 -')
    endfunction

    nnoremap <S-f> :call Autopep8()<CR>
'''

#JavaScript
[[plugins]]
repo = "maxmellon/vim-jsx-pretty"
on_ft = ['javascript', 'javascriptreact', 'typescript', 'typescriptreact']

## TypeScript
[[plugins]]
repo = 'HerringtonDarkholme/yats.vim'
on_ft = ['typescript', 'typescriptreact']

#Toml
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

