[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'mattn/sonictemplate-vim'
hook_add = '''
    let g:sonictemplate_vim_template_dir = "$HOME/.config/nvim/template"
'''

[[plugins]]
repo = 'terryma/vim-multiple-cursors'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
    source ~/.config/nvim/rc/denite.rc.vim
'''

[[plugins]]
repo = 'Shougo/defx.nvim'
hook_add = '''
    source ~/.config/nvim/rc/defx.rc.vim
'''

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'kristijanhusak/defx-icons'

[[plugins]]
repo = 'kristijanhusak/defx-git'

[[plugins]]
repo = 'Shougo/vimproc'
build = 'make'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'vim-scripts/Align'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
merged = '0'
hook_add = '''
    source ~/.config/nvim/rc/coc.rc.vim
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
    source ~/.config/nvim/rc/lightline.rc.vim
'''

[[plugins]]
repo = "nvim-treesitter/nvim-treesitter"
merged = 0
hook_add = '''
    source ~/.config/nvim/rc/nvim-treesitter.rc.vim
'''

[[plugins]]
repo = "bluz71/vim-nightfly-guicolors"
